name: Sparta Nest.js CD

on:
  workflow_dispatch: # 수동 실행
  workflow_run: # 특정 workflow가 실행됐을 때
    workflows: ['Sparta Nest.js CI'] # CI workflow
    types: [completed] # 완료 되었을 때
    branches: [dev] # main 브랜치

jobs:
  deploy:
    # workflow 완료 후 결과가 성공 일 때
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # 작업을 실행 할 VM의 OS 지정
    runs-on: ubuntu-24.04

    # 작업 내의 단위 작업(step)을 정의
    steps:
      - name: Configure SSH for Instance 1
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ec2.key
          chmod 400 ~/.ssh/ec2.key
          cat >>~/.ssh/config <<END
          Host instance1
            HostName 15.164.143.126
            User $SSH_USER
            IdentityFile ~/.ssh/ec2.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_EC2_PEM_KEY }}

      - name: Deploy to EC2 Instance 1
        run: |
          HOST="15.164.143.126"
          SSH_USER="ubuntu"
          
          echo "Deploying to $HOST"
          ssh -o "StrictHostKeyChecking=no" $SSH_USER@$HOST 'cd /home/ubuntu/Give_me_the_ticket && git switch dev && git pull origin dev && echo "${{ secrets.ENV }}" > .env && ./scripts/run.sh'

      - name: Configure SSH for Instance 2
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ec2.key
          chmod 400 ~/.ssh/ec2.key
          cat >>~/.ssh/config <<END
          Host instance2
            HostName 3.39.217.52
            User $SSH_USER
            IdentityFile ~/.ssh/ec2.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_EC2_PEM_KEY }}

      - name: Deploy to EC2 Instance 2
        run: |
          HOST="3.39.217.52"
          SSH_USER="ubuntu"
          
          echo "Deploying to $HOST"
          ssh -o "StrictHostKeyChecking=no" $SSH_USER@$HOST 'cd /home/ubuntu/Give_me_the_ticket && git switch dev && git pull origin dev && echo "${{ secrets.ENV }}" > .env && ./scripts/run.sh'

      - name: Configure SSH for Instance 3
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ec2.key
          chmod 400 ~/.ssh/ec2.key
          cat >>~/.ssh/config <<END
          Host instance3
            HostName 3.35.183.61
            User $SSH_USER
            IdentityFile ~/.ssh/ec2.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_EC2_PEM_KEY }}

      - name: Deploy to EC2 Instance 3
        run: |
          HOST="3.35.183.61"
          SSH_USER="ubuntu"
          
          echo "Deploying to $HOST"
          ssh -o "StrictHostKeyChecking=no" $SSH_USER@$HOST 'cd /home/ubuntu/Give_me_the_ticket && git switch dev && git pull origin dev && echo "${{ secrets.ENV }}" > .env && ./scripts/run.sh'

